-- text expressions
INSERT INTO dictionary_colloquial_expressions(expression, synonym_expression) VALUES ('badanie geotechniczne', 'badanie gruntu');
INSERT INTO dictionary_colloquial_expressions(expression, synonym_expression) VALUES ('badanie geotechniczne', 'badanie hydrogeologiczne');
INSERT INTO dictionary_colloquial_expressions(expression, synonym_expression) VALUES ('budowa nad jeziorem', 'minimalna odległość budynku od linii brzegowej');
INSERT INTO dictionary_colloquial_expressions(expression, synonym_expression) VALUES ('Budowa przy drogach publicznych', 'odległość drogi od obiektów budowlanych');
INSERT INTO dictionary_colloquial_expressions(expression, synonym_expression) VALUES ('Budowa przy drogach publicznych', 'odległość obiektów budowlanych od drogi');
INSERT INTO dictionary_colloquial_expressions(expression, synonym_expression) VALUES ('Budowa przy drogach publicznych', 'budowa przy drogach');
INSERT INTO dictionary_colloquial_expressions(expression, synonym_expression) VALUES ('Budowa przy drogach publicznych', 'uzgodnienie lokalizacji obiektów budowlanych i urządzeń infrastruktury technicznej w pasie drogowym');
INSERT INTO dictionary_colloquial_expressions(expression, synonym_expression) VALUES ('budowa przy linii energetycznej', 'kable energetyczne-minimalne odległości od budynków');
INSERT INTO dictionary_colloquial_expressions(expression, synonym_expression) VALUES ('budowa przy linii energetycznej', 'słupy z liniami energetycznymi-odległości od budynków');
INSERT INTO dictionary_colloquial_expressions(expression, synonym_expression) VALUES ('Budowa przy torach kolejowych', 'odległość od torów kolejowych');
INSERT INTO dictionary_colloquial_expressions(expression, synonym_expression) VALUES ('Budowa przy torach kolejowych', 'odległość torów kolejowych od budynków');
INSERT INTO dictionary_colloquial_expressions(expression, synonym_expression) VALUES ('Budowa przy torach kolejowych', 'budowa przy torach kolejowych');
INSERT INTO dictionary_colloquial_expressions(expression, synonym_expression) VALUES ('budowla', 'budowla-definicja');
INSERT INTO dictionary_colloquial_expressions(expression, synonym_expression) VALUES ('budowla', 'obiekt liniowy-definicja');
INSERT INTO dictionary_colloquial_expressions(expression, synonym_expression) VALUES ('decyzja o lokalizacji inwestycji celu publicznego', 'DLCP');
INSERT INTO dictionary_colloquial_expressions(expression, synonym_expression) VALUES ('decyzja o lokalizacji inwestycji celu publicznego', 'cel publiczny');
INSERT INTO dictionary_colloquial_expressions(expression, synonym_expression) VALUES ('decyzja o lokalizacji inwestycji celu publicznego', 'lokalizacja inwestycji celu publicznego');
INSERT INTO dictionary_colloquial_expressions(expression, synonym_expression) VALUES ('decyzja o lokalizacji inwestycji celu publicznego', 'inwestycja celu publicznego');
INSERT INTO dictionary_colloquial_expressions(expression, synonym_expression) VALUES ('ocena oddziaływania inwestycji na środowisko', 'oddziaływanie inwestycji na środowisko');
INSERT INTO dictionary_colloquial_expressions(expression, synonym_expression) VALUES ('opłata skarbowa za wydanie pozwolenia na budowę', 'opłata skarbowa za zgłoszenie');
INSERT INTO dictionary_colloquial_expressions(expression, synonym_expression) VALUES ('oświadczenie o posiadanym prawie do dysponowania nieruchomością na cele budowlane', 'prawo do dysponowania nieruchomością na cele budowlane');
INSERT INTO dictionary_colloquial_expressions(expression, synonym_expression) VALUES ('pomieszczenia przeznaczone na pobyt ludzi', 'pobyt ludzi w pomieszczeniach');
INSERT INTO dictionary_colloquial_expressions(expression, synonym_expression) VALUES ('pozwolenie na budowę', 'pnb');
INSERT INTO dictionary_colloquial_expressions(expression, synonym_expression) VALUES ('pozwolenie na rozbiórkę', 'zgłoszenie na rozbiórkę');
INSERT INTO dictionary_colloquial_expressions(expression, synonym_expression) VALUES ('pozwolenie wodnoprawne', 'zwykłe korzystanie z wód');
INSERT INTO dictionary_colloquial_expressions(expression, synonym_expression) VALUES ('pozwolenie wodnoprawne', 'szczególne korzystanie z wód');
INSERT INTO dictionary_colloquial_expressions(expression, synonym_expression) VALUES ('przeprowadzenie oceny oddziaływania na obszar NATURA 2000', 'ocena oddziaływania na obszar NATURA 2000');
INSERT INTO dictionary_colloquial_expressions(expression, synonym_expression) VALUES ('przeprowadzenie oceny oddziaływania na obszar NATURA 2000', 'NATURA 2000');
INSERT INTO dictionary_colloquial_expressions(expression, synonym_expression) VALUES ('strefa ochrony konserwatora zabytków', 'strefa archeologiczna');
INSERT INTO dictionary_colloquial_expressions(expression, synonym_expression) VALUES ('strefa ochrony konserwatora zabytków', 'ochrona konserwatorska');
INSERT INTO dictionary_colloquial_expressions(expression, synonym_expression) VALUES ('strefa ochrony konserwatora zabytków', 'ochrona archeologiczna');
INSERT INTO dictionary_colloquial_expressions(expression, synonym_expression) VALUES ('strefa ochrony konserwatora zabytków', 'formy ochrony zabytków');
INSERT INTO dictionary_colloquial_expressions(expression, synonym_expression) VALUES ('uzgodnienie lokalizacji w pasie drogowym obiektów budowlanych lub urządzeń', 'lokalizacja obiektów budowlanych lub urządzeń w pasie drogowym');
INSERT INTO dictionary_colloquial_expressions(expression, synonym_expression) VALUES ('uzgodnienie lokalizacji zjazdu z zarządcą drogi', 'lokalizacja zjazdu');
INSERT INTO dictionary_colloquial_expressions(expression, synonym_expression) VALUES ('uzgodnienia z rzeczoznawcami projektu budowlanego', 'rzeczoznawcy');
INSERT INTO dictionary_colloquial_expressions(expression, synonym_expression) VALUES ('uzgodnienia z rzeczoznawcami projektu budowlanego', 'uzgodnienia BHP');
INSERT INTO dictionary_colloquial_expressions(expression, synonym_expression) VALUES ('uzgodnienia z rzeczoznawcami projektu budowlanego', 'uzgodnienia ppoż');
INSERT INTO dictionary_colloquial_expressions(expression, synonym_expression) VALUES ('uzgodnienia z rzeczoznawcami projektu budowlanego', 'uzgodnienia hig.-sanit.');
INSERT INTO dictionary_colloquial_expressions(expression, synonym_expression) VALUES ('zudp', 'uzgodnienie z zudp');
INSERT INTO dictionary_colloquial_expressions(expression, synonym_expression) VALUES ('zudp', 'zespół uzgodnień dokumentacji projektowej');
INSERT INTO dictionary_colloquial_expressions(expression, synonym_expression) VALUES ('warunki przyłączenia', 'zapewnienie dostawy wody, prądu lub gazu');
INSERT INTO dictionary_colloquial_expressions(expression, synonym_expression) VALUES ('warunki przyłączenia', 'wniosek o zapewnienie dostaw wody, prądu lub gazu');
INSERT INTO dictionary_colloquial_expressions(expression, synonym_expression) VALUES ('warunki przyłączenia', 'wniosek o warunki przyłączenia');
INSERT INTO dictionary_colloquial_expressions(expression, synonym_expression) VALUES ('warunki przyłączenia', 'podłączenie do sieci wod-kan');
INSERT INTO dictionary_colloquial_expressions(expression, synonym_expression) VALUES ('warunki przyłączenia', 'podłączenie do sieci elektroenergetycznej');
INSERT INTO dictionary_colloquial_expressions(expression, synonym_expression) VALUES ('warunki przyłączenia', 'podłączenie do sieci gazowej');
INSERT INTO dictionary_colloquial_expressions(expression, synonym_expression) VALUES ('warunki zabudowy', 'decyzja o warunkach ');
INSERT INTO dictionary_colloquial_expressions(expression, synonym_expression) VALUES ('warunki zabudowy', 'wz');
INSERT INTO dictionary_colloquial_expressions(expression, synonym_expression) VALUES ('wycinka drzew lub krzewów', 'zgoda na wycinkę drzew lub krzewów');
INSERT INTO dictionary_colloquial_expressions(expression, synonym_expression) VALUES ('wycinka drzew lub krzewów', 'zezwolenie na wycinkę drzew lub krzewów');
INSERT INTO dictionary_colloquial_expressions(expression, synonym_expression) VALUES ('wycinka drzew lub krzewów', 'decyzja zezwalająca na wycinkę drzew lub krzewów');
INSERT INTO dictionary_colloquial_expressions(expression, synonym_expression) VALUES ('wyłączenie gruntów z produkcji leśnej', 'odlesienie');
INSERT INTO dictionary_colloquial_expressions(expression, synonym_expression) VALUES ('wyłączenie gruntów z produkcji rolnej', 'odrolnienie');
INSERT INTO dictionary_colloquial_expressions(expression, synonym_expression) VALUES ('zezwolenie na prowadzenie robót budowlanych w pasie drogowym', 'pozwolenie na prowadzenie robót budowlanych w pasie drogowym');
INSERT INTO dictionary_colloquial_expressions(expression, synonym_expression) VALUES ('zgłoszenie budowlane', 'procedury budowlane wymagające zgłoszenia');

--expressions
INSERT INTO dictionary_colloquial_expressions(expression, synonym_expression) VALUES ('służebność drogowa', 'droga konieczna');
INSERT INTO dictionary_colloquial_expressions(expression, synonym_expression) VALUES ('rów-zasypanie rowu melioracyjnego', 'zasypanie rowu melioracyjnego');
INSERT INTO dictionary_colloquial_expressions(expression, synonym_expression) VALUES ('rów-zasypanie rowu melioracyjnego', 'likwidacja rowu');
INSERT INTO dictionary_colloquial_expressions(expression, synonym_expression) VALUES ('rów-zasypanie rowu melioracyjnego', 'odprowadzenie wód deszczowych do rowu');
INSERT INTO dictionary_colloquial_expressions(expression, synonym_expression) VALUES ('rów-zasypanie rowu melioracyjnego', 'kanalizacja deszczowa-odprowadzenie wód do rowu');
INSERT INTO dictionary_colloquial_expressions(expression, synonym_expression) VALUES ('odprowadzenie wód deszczowych na teren nieutwardzony', 'kanalizacja deszczowa-odprowadzenie wód na teren nieutwardzony');
INSERT INTO dictionary_colloquial_expressions(expression, synonym_expression) VALUES ('odprowadzenie wód deszczowych na teren nieutwardzony', 'instalacja kanalizacji deszczowej-odprowadzenie wód na teren nieutwardzony');
INSERT INTO dictionary_colloquial_expressions(expression, synonym_expression) VALUES ('odprowadzenie wód deszczowych na teren nieutwardzony', 'wprowadzanie ścieków deszczowych do gruntu');
INSERT INTO dictionary_colloquial_expressions(expression, synonym_expression) VALUES ('odprowadzenie wód deszczowych do zbiornika', 'kanalizacja deszczowa-odprowadzenie wód do zbiornika');
INSERT INTO dictionary_colloquial_expressions(expression, synonym_expression) VALUES ('odprowadzenie wód deszczowych do zbiornika', 'instalacja kanalizacji deszczowej-odprowadzenie wód do zbiornika');
INSERT INTO dictionary_colloquial_expressions(expression, synonym_expression) VALUES ('odprowadzanie wód deszczowych do sieci kanalizacji deszczowej', 'kanalizacja deszczowa-odprowadzenie wód do sieci');
INSERT INTO dictionary_colloquial_expressions(expression, synonym_expression) VALUES ('odprowadzanie wód deszczowych do sieci kanalizacji deszczowej', 'wprowadzanie ścieków deszczowych do sieci');
INSERT INTO dictionary_colloquial_expressions(expression, synonym_expression) VALUES ('odprowadzenie ścieków socjalnych do sieci kanalizacji sanitarnej', 'kanalizacja sanitarna-odprowadzenie ścieków do sieci');
INSERT INTO dictionary_colloquial_expressions(expression, synonym_expression) VALUES ('odprowadzenie ścieków socjalnych do sieci kanalizacji sanitarnej', 'wprowadzanie ścieków socjalnych do sieci');
INSERT INTO dictionary_colloquial_expressions(expression, synonym_expression) VALUES ('rozbudowa', 'aneks - rozbudowa budynku o nowe pomieszczenie');
INSERT INTO dictionary_colloquial_expressions(expression, synonym_expression) VALUES ('rozbudowa', 'przybudówka - rozbudowa obiektu istniejącego o nowe pomieszczenia');
INSERT INTO dictionary_colloquial_expressions(expression, synonym_expression) VALUES ('rozbudowa', 'skrzydło - rozbudowa budynku o nowe pomieszczenie');
INSERT INTO dictionary_colloquial_expressions(expression, synonym_expression) VALUES ('rozbudowa', 'ganek - rozbudowa budynku o nowe pomieszczenie');
INSERT INTO dictionary_colloquial_expressions(expression, synonym_expression) VALUES ('rozbudowa', 'garaż-rozbudowa obiektu istniejącego o garaż');
INSERT INTO dictionary_colloquial_expressions(expression, synonym_expression) VALUES ('remont', 'konserwacja');
INSERT INTO dictionary_colloquial_expressions(expression, synonym_expression) VALUES ('docieplenie budynków', 'ocieplenie budynków');
INSERT INTO dictionary_colloquial_expressions(expression, synonym_expression) VALUES ('roboty podczyszczeniowe dna', 'podczyszczanie dna');
INSERT INTO dictionary_colloquial_expressions(expression, synonym_expression) VALUES ('roboty podczyszczeniowe dna', 'czyszczenie dna');
INSERT INTO dictionary_colloquial_expressions(expression, synonym_expression) VALUES ('instalowanie krat na obiektach budowlanych', 'kraty na obiektach budowlanych');
INSERT INTO dictionary_colloquial_expressions(expression, synonym_expression) VALUES ('instalowanie krat na obiektach budowlanych', 'montaż krat');
INSERT INTO dictionary_colloquial_expressions(expression, synonym_expression) VALUES ('instalowanie urządzeń na obiektach budowlanych', 'urządzenia na budynkach');
INSERT INTO dictionary_colloquial_expressions(expression, synonym_expression) VALUES ('instalowanie urządzeń na obiektach budowlanych', 'budowa anten na budynkach');
INSERT INTO dictionary_colloquial_expressions(expression, synonym_expression) VALUES ('instalowanie urządzeń na obiektach budowlanych', 'montaż anten na budynkach');
INSERT INTO dictionary_colloquial_expressions(expression, synonym_expression) VALUES ('instalowanie urządzeń na obiektach budowlanych', 'anteny na budynkach');
INSERT INTO dictionary_colloquial_expressions(expression, synonym_expression) VALUES ('montaż wolno stojących kolektorów słonecznych', 'kolektory słoneczne');
INSERT INTO dictionary_colloquial_expressions(expression, synonym_expression) VALUES ('montaż wolno stojących kolektorów słonecznych', 'wolnostojące kolektory słoneczne');

-- buildings
INSERT INTO dictionary_colloquial_expressions(expression, synonym_expression) VALUES ('Budynek gospodarczy - zaplecze do utrzymania linii kolejowych', 'zaplecze do utrzymania linii kolejowych');
INSERT INTO dictionary_colloquial_expressions(expression, synonym_expression) VALUES ('Budynek mieszkalny jednorodzinny', 'dom jednorodzinny');
INSERT INTO dictionary_colloquial_expressions(expression, synonym_expression) VALUES ('Budynek mieszkalny wielorodzinny', 'dom wielorodzinny');
INSERT INTO dictionary_colloquial_expressions(expression, synonym_expression) VALUES ('Budynek zamieszkania zbiorowego', 'hotel');
INSERT INTO dictionary_colloquial_expressions(expression, synonym_expression) VALUES ('Budynek zamieszkania zbiorowego', 'budynek hotelowy');
INSERT INTO dictionary_colloquial_expressions(expression, synonym_expression) VALUES ('Budynek zamieszkania zbiorowego', 'motel');
INSERT INTO dictionary_colloquial_expressions(expression, synonym_expression) VALUES ('Budynek zamieszkania zbiorowego', 'pensjonat');
INSERT INTO dictionary_colloquial_expressions(expression, synonym_expression) VALUES ('Budynek zamieszkania zbiorowego', 'dom wypoczynkowy');
INSERT INTO dictionary_colloquial_expressions(expression, synonym_expression) VALUES ('Budynek zamieszkania zbiorowego', 'dom wycieczkowy');
INSERT INTO dictionary_colloquial_expressions(expression, synonym_expression) VALUES ('Budynek zamieszkania zbiorowego', 'schronisko');
INSERT INTO dictionary_colloquial_expressions(expression, synonym_expression) VALUES ('Budynek zamieszkania zbiorowego', 'schronisko młodzieżowe');
INSERT INTO dictionary_colloquial_expressions(expression, synonym_expression) VALUES ('Budynek zamieszkania zbiorowego', 'internat');
INSERT INTO dictionary_colloquial_expressions(expression, synonym_expression) VALUES ('Budynek zamieszkania zbiorowego', 'dom studencki');
INSERT INTO dictionary_colloquial_expressions(expression, synonym_expression) VALUES ('Budynek zamieszkania zbiorowego', 'koszary');
INSERT INTO dictionary_colloquial_expressions(expression, synonym_expression) VALUES ('Budynek zamieszkania zbiorowego', 'budynek koszarowy');
INSERT INTO dictionary_colloquial_expressions(expression, synonym_expression) VALUES ('Budynek zamieszkania zbiorowego', 'dom dziecka');
INSERT INTO dictionary_colloquial_expressions(expression, synonym_expression) VALUES ('Budynek zamieszkania zbiorowego', 'dom starców');
INSERT INTO dictionary_colloquial_expressions(expression, synonym_expression) VALUES ('Budynek zamieszkania zbiorowego', 'dom rencistów');
INSERT INTO dictionary_colloquial_expressions(expression, synonym_expression) VALUES ('Budynek zamieszkania zbiorowego', 'dom zakonny');
INSERT INTO dictionary_colloquial_expressions(expression, synonym_expression) VALUES ('Budynek zamieszkania zbiorowego', 'budynek zakonny');
INSERT INTO dictionary_colloquial_expressions(expression, synonym_expression) VALUES ('Budynek użyteczności publicznej', 'budynek  administracji publicznej');
INSERT INTO dictionary_colloquial_expressions(expression, synonym_expression) VALUES ('Budynek użyteczności publicznej', 'budynek wymiaru sprawiedliwości');
INSERT INTO dictionary_colloquial_expressions(expression, synonym_expression) VALUES ('Budynek użyteczności publicznej', 'budynek kultury');
INSERT INTO dictionary_colloquial_expressions(expression, synonym_expression) VALUES ('Budynek użyteczności publicznej', 'budynek kultu religijnego');
INSERT INTO dictionary_colloquial_expressions(expression, synonym_expression) VALUES ('Budynek użyteczności publicznej', 'kościół');
INSERT INTO dictionary_colloquial_expressions(expression, synonym_expression) VALUES ('Budynek użyteczności publicznej', 'budynek oświaty');
INSERT INTO dictionary_colloquial_expressions(expression, synonym_expression) VALUES ('Budynek użyteczności publicznej', 'szkoła');
INSERT INTO dictionary_colloquial_expressions(expression, synonym_expression) VALUES ('Budynek użyteczności publicznej', 'budynek szkoły');
INSERT INTO dictionary_colloquial_expressions(expression, synonym_expression) VALUES ('Budynek użyteczności publicznej', 'budynek szkolnictwa wyższego');
INSERT INTO dictionary_colloquial_expressions(expression, synonym_expression) VALUES ('Budynek użyteczności publicznej', 'budynek nauki');
INSERT INTO dictionary_colloquial_expressions(expression, synonym_expression) VALUES ('Budynek użyteczności publicznej', 'budynek wychowania');
INSERT INTO dictionary_colloquial_expressions(expression, synonym_expression) VALUES ('Budynek użyteczności publicznej', 'dom wychowawczy');
INSERT INTO dictionary_colloquial_expressions(expression, synonym_expression) VALUES ('Budynek użyteczności publicznej', 'budynek opieki zdrowotnej');
INSERT INTO dictionary_colloquial_expressions(expression, synonym_expression) VALUES ('Budynek użyteczności publicznej', 'dom opieki zdrowotnej');
INSERT INTO dictionary_colloquial_expressions(expression, synonym_expression) VALUES ('Budynek użyteczności publicznej', 'budynek opieki społecznej');
INSERT INTO dictionary_colloquial_expressions(expression, synonym_expression) VALUES ('Budynek użyteczności publicznej', 'dom opieki społecznej');
INSERT INTO dictionary_colloquial_expressions(expression, synonym_expression) VALUES ('Budynek użyteczności publicznej', 'budynek obsługi bankowej');
INSERT INTO dictionary_colloquial_expressions(expression, synonym_expression) VALUES ('Budynek użyteczności publicznej', 'bank');
INSERT INTO dictionary_colloquial_expressions(expression, synonym_expression) VALUES ('Budynek użyteczności publicznej', 'budynek obsługi handlu');
INSERT INTO dictionary_colloquial_expressions(expression, synonym_expression) VALUES ('Budynek użyteczności publicznej', 'sklep');
INSERT INTO dictionary_colloquial_expressions(expression, synonym_expression) VALUES ('Budynek użyteczności publicznej', 'budynek gastronomii');
INSERT INTO dictionary_colloquial_expressions(expression, synonym_expression) VALUES ('Budynek użyteczności publicznej', 'restauracja');
INSERT INTO dictionary_colloquial_expressions(expression, synonym_expression) VALUES ('Budynek użyteczności publicznej', 'kawiarnia');
INSERT INTO dictionary_colloquial_expressions(expression, synonym_expression) VALUES ('Budynek użyteczności publicznej', 'bar');
INSERT INTO dictionary_colloquial_expressions(expression, synonym_expression) VALUES ('Budynek użyteczności publicznej', 'budynek usług');
INSERT INTO dictionary_colloquial_expressions(expression, synonym_expression) VALUES ('Budynek użyteczności publicznej', 'budynek usług pocztowych');
INSERT INTO dictionary_colloquial_expressions(expression, synonym_expression) VALUES ('Budynek użyteczności publicznej', 'poczta');
INSERT INTO dictionary_colloquial_expressions(expression, synonym_expression) VALUES ('Budynek użyteczności publicznej', 'budynek usług telekomunikacyjnych');
INSERT INTO dictionary_colloquial_expressions(expression, synonym_expression) VALUES ('Budynek użyteczności publicznej', 'budynek turystyki');
INSERT INTO dictionary_colloquial_expressions(expression, synonym_expression) VALUES ('Budynek użyteczności publicznej', 'budynek sportu');
INSERT INTO dictionary_colloquial_expressions(expression, synonym_expression) VALUES ('Budynek użyteczności publicznej', 'budynek obsługi pasażerów w transporcie kolejowym');
INSERT INTO dictionary_colloquial_expressions(expression, synonym_expression) VALUES ('Budynek użyteczności publicznej', 'dworzec');
INSERT INTO dictionary_colloquial_expressions(expression, synonym_expression) VALUES ('Budynek użyteczności publicznej', 'port lotniczy');
INSERT INTO dictionary_colloquial_expressions(expression, synonym_expression) VALUES ('Budynek użyteczności publicznej', 'budynek obsługi pasażerów w transporcie drogowym');
INSERT INTO dictionary_colloquial_expressions(expression, synonym_expression) VALUES ('Budynek użyteczności publicznej', 'budynek obsługi pasażerów w transporcie lotniczym');
INSERT INTO dictionary_colloquial_expressions(expression, synonym_expression) VALUES ('Budynek użyteczności publicznej', 'budynek obsługi pasażerów w transporcie morskim');
INSERT INTO dictionary_colloquial_expressions(expression, synonym_expression) VALUES ('Budynek użyteczności publicznej', 'port');
INSERT INTO dictionary_colloquial_expressions(expression, synonym_expression) VALUES ('Budynek użyteczności publicznej', 'budynek obsługi pasażerów w transporcie wodnym śródlądowym');
INSERT INTO dictionary_colloquial_expressions(expression, synonym_expression) VALUES ('Budynek użyteczności publicznej', 'budynek biurowy');
INSERT INTO dictionary_colloquial_expressions(expression, synonym_expression) VALUES ('Budynek użyteczności publicznej', 'biuro');
INSERT INTO dictionary_colloquial_expressions(expression, synonym_expression) VALUES ('Budynek użyteczności publicznej', 'budynek socjalny');
INSERT INTO dictionary_colloquial_expressions(expression, synonym_expression) VALUES ('Budynek użyteczności publicznej', 'szpital');
INSERT INTO dictionary_colloquial_expressions(expression, synonym_expression) VALUES ('Budynek użyteczności publicznej', 'kino');
INSERT INTO dictionary_colloquial_expressions(expression, synonym_expression) VALUES ('Budynek użyteczności publicznej', 'teatr');
INSERT INTO dictionary_colloquial_expressions(expression, synonym_expression) VALUES ('Budynek użyteczności publicznej', 'centrum handlowe');
INSERT INTO dictionary_colloquial_expressions(expression, synonym_expression) VALUES ('budynek rekreacji indywidualnej', 'budynek letniskowy');
INSERT INTO dictionary_colloquial_expressions(expression, synonym_expression) VALUES ('budynek rekreacji indywidualnej', 'budynek letni');
INSERT INTO dictionary_colloquial_expressions(expression, synonym_expression) VALUES ('droga wewnętrzna', 'droga prywatna');
INSERT INTO dictionary_colloquial_expressions(expression, synonym_expression) VALUES ('wodociąg', 'sieć wodociągowa');
INSERT INTO dictionary_colloquial_expressions(expression, synonym_expression) VALUES ('wodociąg', 'budowa wodociągu');
INSERT INTO dictionary_colloquial_expressions(expression, synonym_expression) VALUES ('gazociąg', 'sieć gazowa');
INSERT INTO dictionary_colloquial_expressions(expression, synonym_expression) VALUES ('ciepłociąg', 'sieć ciepłownicza');
INSERT INTO dictionary_colloquial_expressions(expression, synonym_expression) VALUES ('wolnostojący maszt antenowy', 'stacja bazowa telefonii komórkowej');
INSERT INTO dictionary_colloquial_expressions(expression, synonym_expression) VALUES ('tama', 'zapora');
INSERT INTO dictionary_colloquial_expressions(expression, synonym_expression) VALUES ('kompostownik', 'wał z ziemi i roślin');
INSERT INTO dictionary_colloquial_expressions(expression, synonym_expression) VALUES ('kompostownik', 'usypany z ziemi i roślin wał');
INSERT INTO dictionary_colloquial_expressions(expression, synonym_expression) VALUES ('kompostownik', 'silos (kompostownik)');
INSERT INTO dictionary_colloquial_expressions(expression, synonym_expression) VALUES ('instalacja zbiornikowa na gaz płynny', 'zbiornik na gaz');
INSERT INTO dictionary_colloquial_expressions(expression, synonym_expression) VALUES ('instalacja wentylacji i klimatyzacji', 'wentylacja');
INSERT INTO dictionary_colloquial_expressions(expression, synonym_expression) VALUES ('instalacja wentylacji i klimatyzacji', 'klimatyzacja');
INSERT INTO dictionary_colloquial_expressions(expression, synonym_expression) VALUES ('instalacja kanalizacji sanitarnej', 'kanalizacja sanitarna-budowa instalacji ');
INSERT INTO dictionary_colloquial_expressions(expression, synonym_expression) VALUES ('instalacja kanalizacji deszczowej', 'kanalizacja deszczowa-budowa instalacji');
INSERT INTO dictionary_colloquial_expressions(expression, synonym_expression) VALUES ('sieć kanalizacji sanitarnej', 'kanalizacja sanitarna - budowa sieci');
INSERT INTO dictionary_colloquial_expressions(expression, synonym_expression) VALUES ('sieć kanalizacji deszczowej', 'kanalizacja deszczowa - budowa sieci');
INSERT INTO dictionary_colloquial_expressions(expression, synonym_expression) VALUES ('śmietnik', 'smietnik');
INSERT INTO dictionary_colloquial_expressions(expression, synonym_expression) VALUES ('śmietnik', 'pojemnik służący do czasowego gromadzenia odpadów stałych-śmietnik');
INSERT INTO dictionary_colloquial_expressions(expression, synonym_expression) VALUES ('zbiornik bezodpływowy na nieczystości ciekłe', 'zbiornik na ścieki');
INSERT INTO dictionary_colloquial_expressions(expression, synonym_expression) VALUES ('zbiornik bezodpływowy na nieczystości ciekłe', 'szambo');
INSERT INTO dictionary_colloquial_expressions(expression, synonym_expression) VALUES ('zbiornik bezodpływowy na nieczystości ciekłe', 'odprowadzenie ścieków socjalnych do zbiornika bezodpływowego');
INSERT INTO dictionary_colloquial_expressions(expression, synonym_expression) VALUES ('indywidualne ujęcie wody - studnia', 'studnia');
INSERT INTO dictionary_colloquial_expressions(expression, synonym_expression) VALUES ('indywidualne ujęcie wody - studnia', 'obudowa ujęć wód podziemnych');
INSERT INTO dictionary_colloquial_expressions(expression, synonym_expression) VALUES ('przydomowa oczyszczalnia ścieków', 'oczyszczalnia ścieków-przydomowa');
INSERT INTO dictionary_colloquial_expressions(expression, synonym_expression) VALUES ('przydomowa oczyszczalnia ścieków', 'indywidualna oczyszczalnia ścieków');
INSERT INTO dictionary_colloquial_expressions(expression, synonym_expression) VALUES ('przejścia dla pieszych naziemne i podziemne', 'estakada');
INSERT INTO dictionary_colloquial_expressions(expression, synonym_expression) VALUES ('przejścia dla pieszych naziemne i podziemne', 'most');
INSERT INTO dictionary_colloquial_expressions(expression, synonym_expression) VALUES ('przejścia dla pieszych naziemne i podziemne', 'wiadukt');
INSERT INTO dictionary_colloquial_expressions(expression, synonym_expression) VALUES ('przejścia dla pieszych naziemne i podziemne', 'obiekt mostowy');
INSERT INTO dictionary_colloquial_expressions(expression, synonym_expression) VALUES ('boisko', 'boisko szkolne');
INSERT INTO dictionary_colloquial_expressions(expression, synonym_expression) VALUES ('boisko', 'kort tenisowy');
INSERT INTO dictionary_colloquial_expressions(expression, synonym_expression) VALUES ('boisko', 'bieżnia');
INSERT INTO dictionary_colloquial_expressions(expression, synonym_expression) VALUES ('miejsca postojowe', 'parking');
INSERT INTO dictionary_colloquial_expressions(expression, synonym_expression) VALUES ('basen', 'oczko wodne-przydomowe');
INSERT INTO dictionary_colloquial_expressions(expression, synonym_expression) VALUES ('wodotrysk', 'fontanna');
INSERT INTO dictionary_colloquial_expressions(expression, synonym_expression) VALUES ('posterunki wodowskazowe', 'posterunki meteorologiczne');
INSERT INTO dictionary_colloquial_expressions(expression, synonym_expression) VALUES ('posterunki wodowskazowe', 'posterunki opadowe');
INSERT INTO dictionary_colloquial_expressions(expression, synonym_expression) VALUES ('posterunki wodowskazowe', 'posterunki wód podziemnych');
INSERT INTO dictionary_colloquial_expressions(expression, synonym_expression) VALUES ('posterunki wodowskazowe', 'punkty obserwacyjne stanów wód podziemnych');
INSERT INTO dictionary_colloquial_expressions(expression, synonym_expression) VALUES ('posterunki wodowskazowe', 'punkty monitoringu jakości wód podziemnych');
INSERT INTO dictionary_colloquial_expressions(expression, synonym_expression) VALUES ('posterunki wodowskazowe', 'punkty piezometrów obserwacyjnych');
INSERT INTO dictionary_colloquial_expressions(expression, synonym_expression) VALUES ('posterunki wodowskazowe', 'punkty obudowanych źródeł');
INSERT INTO dictionary_colloquial_expressions(expression, synonym_expression) VALUES ('liny brzegowe', 'sztuczne umocnienia brzegów');
INSERT INTO dictionary_colloquial_expressions(expression, synonym_expression) VALUES ('liny brzegowe', 'powierzchniowe umocnienia brzegów');
INSERT INTO dictionary_colloquial_expressions(expression, synonym_expression) VALUES ('liny brzegowe', 'liniowe umocnienia brzegów');
INSERT INTO dictionary_colloquial_expressions(expression, synonym_expression) VALUES ('liny brzegowe', 'opaski brzegowe');
INSERT INTO dictionary_colloquial_expressions(expression, synonym_expression) VALUES ('liny brzegowe', 'umocnienia brzegów');
INSERT INTO dictionary_colloquial_expressions(expression, synonym_expression) VALUES ('znaki geodezyjne', 'obiekty triangulacyjne');
INSERT INTO dictionary_colloquial_expressions(expression, synonym_expression) VALUES ('urządzenia melioracji wodnej', 'rowy-budowa');
INSERT INTO dictionary_colloquial_expressions(expression, synonym_expression) VALUES ('urządzenia melioracji wodnej', 'budowa rowów');
INSERT INTO dictionary_colloquial_expressions(expression, synonym_expression) VALUES ('urządzenia melioracji wodnej', 'stawy hodowlane');
INSERT INTO dictionary_colloquial_expressions(expression, synonym_expression) VALUES ('urządzenia melioracji wodnej', 'ziemne stawy rybne');
INSERT INTO dictionary_colloquial_expressions(expression, synonym_expression) VALUES ('urządzenia melioracji wodnej', 'zbiorniki wodne');
INSERT INTO dictionary_colloquial_expressions(expression, synonym_expression) VALUES ('urządzenia melioracji wodnej', 'oczko wodne-staw hodowlany');
INSERT INTO dictionary_colloquial_expressions(expression, synonym_expression) VALUES ('budowle przeciwpowodziowe', 'wały przeciwpowodziowe');
INSERT INTO dictionary_colloquial_expressions(expression, synonym_expression) VALUES ('wykonywanie ujęć wód śródlądowych powierzchniowych', 'ujęcia wód śródlądowych powierzchniowych');
INSERT INTO dictionary_colloquial_expressions(expression, synonym_expression) VALUES ('ogród zimowy', 'oranżeria');
INSERT INTO dictionary_colloquial_expressions(expression, synonym_expression) VALUES ('ogród zimowy', 'oranżeria przydomowa');
INSERT INTO dictionary_colloquial_expressions(expression, synonym_expression) VALUES ('wiata na działkach w rodzinnych ogrodach działkowych', 'altana');
INSERT INTO dictionary_colloquial_expressions(expression, synonym_expression) VALUES ('wiata na samochód', 'garaż-wiata');
INSERT INTO dictionary_colloquial_expressions(expression, synonym_expression) VALUES ('wiata na samochód', 'wiata');
INSERT INTO dictionary_colloquial_expressions(expression, synonym_expression) VALUES ('kapliczka', 'krzyż przydrożny');
INSERT INTO dictionary_colloquial_expressions(expression, synonym_expression) VALUES ('kapliczka', 'figurka');
INSERT INTO dictionary_colloquial_expressions(expression, synonym_expression) VALUES ('kapliczka', 'posąg');
INSERT INTO dictionary_colloquial_expressions(expression, synonym_expression) VALUES ('kapliczka', 'wodotrysk');
INSERT INTO dictionary_colloquial_expressions(expression, synonym_expression) VALUES ('kapliczka', 'obiekt architektury ogrodowej');
INSERT INTO dictionary_colloquial_expressions(expression, synonym_expression) VALUES ('kapliczka', 'piaskownica');
INSERT INTO dictionary_colloquial_expressions(expression, synonym_expression) VALUES ('kapliczka', 'huśtawka');
INSERT INTO dictionary_colloquial_expressions(expression, synonym_expression) VALUES ('kapliczka', 'drabinka');
INSERT INTO dictionary_colloquial_expressions(expression, synonym_expression) VALUES ('kapliczka', 'śmietnik');
INSERT INTO dictionary_colloquial_expressions(expression, synonym_expression) VALUES ('kapliczka', 'obiekt użytkowy służący codziennej rekreacji');
INSERT INTO dictionary_colloquial_expressions(expression, synonym_expression) VALUES ('kapliczka', 'obiekt użytkowy służący utrzymania porządku');
INSERT INTO dictionary_colloquial_expressions(expression, synonym_expression) VALUES ('kapliczka', 'obiekt małej architektury');
INSERT INTO dictionary_colloquial_expressions(expression, synonym_expression) VALUES ('tymczasowy obiekt budowlany', 'strzelnica');
INSERT INTO dictionary_colloquial_expressions(expression, synonym_expression) VALUES ('tymczasowy obiekt budowlany', 'kiosk');
INSERT INTO dictionary_colloquial_expressions(expression, synonym_expression) VALUES ('tymczasowy obiekt budowlany', 'pawilony sprzedaży ulicznej i wystawowe');
INSERT INTO dictionary_colloquial_expressions(expression, synonym_expression) VALUES ('tymczasowy obiekt budowlany', 'przekrycia namiotowe');
INSERT INTO dictionary_colloquial_expressions(expression, synonym_expression) VALUES ('tymczasowy obiekt budowlany', 'powłoki pneumatyczne');
INSERT INTO dictionary_colloquial_expressions(expression, synonym_expression) VALUES ('plac zabaw', 'urządzenia rozrywkowe');
INSERT INTO dictionary_colloquial_expressions(expression, synonym_expression) VALUES ('plac zabaw', 'obiekty użytkowe służące rekreacji codziennej');
INSERT INTO dictionary_colloquial_expressions(expression, synonym_expression) VALUES ('barakowozy - użytkowane w trakcie realizacji robót budowlanych', 'barakowozy - użytkowane w trakcie badań geologicznych i pomiarów geodezyjnych');
INSERT INTO dictionary_colloquial_expressions(expression, synonym_expression) VALUES ('barakowozy - użytkowane w trakcie realizacji robót budowlanych', 'kontener - tymczasowo użytkowany w trakcie realizacji robót budowlanych');
INSERT INTO dictionary_colloquial_expressions(expression, synonym_expression) VALUES ('barakowozy - użytkowane w trakcie realizacji robót budowlanych', 'obiekty - użytkowane w trakcie realizacji robót budowlanych');
INSERT INTO dictionary_colloquial_expressions(expression, synonym_expression) VALUES ('kontener biurowy', 'kontener socjalny');
INSERT INTO dictionary_colloquial_expressions(expression, synonym_expression) VALUES ('kontener biurowy', 'kontener usługowy');
INSERT INTO dictionary_colloquial_expressions(expression, synonym_expression) VALUES ('kontener biurowy', 'kontener gastronomii');
INSERT INTO dictionary_colloquial_expressions(expression, synonym_expression) VALUES ('reklama', 'tablica reklamowa');
INSERT INTO dictionary_colloquial_expressions(expression, synonym_expression) VALUES ('reklama', 'urządzenia reklamowe');
INSERT INTO dictionary_colloquial_expressions(expression, synonym_expression) VALUES ('ogrodzenie', 'płot');
INSERT INTO dictionary_colloquial_expressions(expression, synonym_expression) VALUES ('ogrodzenie', 'furtka w ogrodzeniu');
INSERT INTO dictionary_colloquial_expressions(expression, synonym_expression) VALUES ('ogrodzenie', 'brama w ogrodzeniu');
